version: '3'
services:
  database:
    image: mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./docker_data/mongo:/data/db
  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./docker_data/redis:/data
  #   environment:
  #     - REDIS_PASSWORD=approveWithdraw
  #   command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"